spring:
  application:
    name: vkm-backend


  datasource:
    url: jdbc:postgresql://localhost:5432/kvmdb
    username: kvmadm
    password: 5963593
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

    refresh-token:
      expiration: 8

