CREATE TABLE refresh_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    token_hash   VARCHAR(64)                             NOT NULL,
    token_family VARCHAR(36)                             NOT NULL,
    expires_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    last_used_at TIMESTAMP(6) WITHOUT TIME ZONE,
    revoked_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_tokenhash UNIQUE (token_hash);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);