CREATE TABLE teams
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id         BIGINT                                  NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    team_size        INTEGER                                 NOT NULL,
    composition_hash VARCHAR(64)                             NOT NULL,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id),
    CONSTRAINT FK_TEAMS_GROUPS FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT uq_teams_group_id_composition_hash UNIQUE (group_id, composition_hash )

);

