CREATE TABLE team_members
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teams_id         BIGINT                                  NOT NULL,
    group_members_id BIGINT                                  NOT NULL,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_team_members PRIMARY KEY (id),
    CONSTRAINT FK_TEAM_MEMBERS_GROUP_MEMBERS FOREIGN KEY (group_members_id)
        REFERENCES group_members (id) ON DELETE CASCADE,
    CONSTRAINT FK_TEAM_MEMBERS_TEAMS FOREIGN KEY (teams_id)
        REFERENCES teams (id) ON DELETE CASCADE,
    CONSTRAINT uk_team_member
        UNIQUE (teams_id, group_members_id)
);

