CREATE TABLE groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    active      INTEGER                                 NOT NULL DEFAULT 1,
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id),
    CONSTRAINT fk_group_members_created_by
        FOREIGN KEY (created_by)
            REFERENCES users(id),

    CONSTRAINT fk_group_members_updated_by
        FOREIGN KEY (updated_by)
            REFERENCES users(id)
);