CREATE TABLE group_members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id    BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    role        VARCHAR(20)                             NOT NULL DEFAULT 'MEMBER'
                                                       CHECK (role IN ('ADMIN', 'MEMBER')),
    status      VARCHAR(20)                             NOT NULL DEFAULT 'PENDING'
                                                        CHECK (status IN (
                                                                         'APPROVED',
                                                                         'PENDING',
                                                                         'REJECTED',
                                                                         'SUSPENDED'
            )),
    approved_by BIGINT,
    approved_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id),
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT FK_GROUP_MEMBERS_APPROVED_BY FOREIGN KEY (approved_by) REFERENCES users (id),
    CONSTRAINT FK_GROUP_MEMBERS_GROUP FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT FK_GROUP_MEMBERS_USER FOREIGN KEY (user_id) REFERENCES users (id)
);

