CREATE TABLE tournaments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    group_id    BIGINT                                  NOT NULL,
    description VARCHAR(255),
    start_date  date,
    end_date    date,
    status      VARCHAR(255)                            NOT NULL,
    format      VARCHAR(255)                            NOT NULL,
    created_by  BIGINT                                  NOT NULL,
    updated_by  BIGINT,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,

    CONSTRAINT pk_tournaments PRIMARY KEY (id),

    CONSTRAINT FK_TOURNAMENTS_GROUPS FOREIGN KEY (group_id) REFERENCES groups (id),

    FOREIGN KEY (created_by)
        REFERENCES users(id),

    FOREIGN KEY (updated_by)
        REFERENCES users(id),

    FOREIGN KEY (group_id)
        REFERENCES groups(id),

        CHECK (
        end_date IS NULL
        OR start_date IS NULL
        OR end_date >= start_date
        )
);

