CREATE TABLE tournament_stages
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT                                  NOT NULL,
    name          VARCHAR(255),
    stage_type    VARCHAR(255),
    stage_order   INTEGER,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_tournament_stages PRIMARY KEY (id),
    CONSTRAINT FK_TOURNAMENT_STAGES_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournaments (id)
        ON DELETE CASCADE,
    UNIQUE (
            tournament_id,
            stage_order
        )
);

