CREATE TABLE tournaments_teams
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id BIGINT                                  NOT NULL,
    team_id       BIGINT                                  NOT NULL,
    seed          INTEGER,
    status        VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_tournaments_teams PRIMARY KEY (id),
    CONSTRAINT FK_TOURNAMENTS_TEAMS_TEAMS FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT FK_TOURNAMENTS_TEAMS_TOURNAMENTS FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    UNIQUE (
            tournament_id,
            team_id
        )
);



